# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.srcs/sources_1/ip/xcv_hdmi/xcv_hdmi.xci
# IP: The module: 'xcv_hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/xcv_hdmi/synth/xcv_hdmi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcv_hdmi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/xcv_hdmi/synth/xcv_hdmi.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcv_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.srcs/sources_1/ip/xcv_hdmi/xcv_hdmi.xci
# IP: The module: 'xcv_hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/xcv_hdmi/synth/xcv_hdmi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcv_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/xcv_hdmi/synth/xcv_hdmi.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcv_hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
