# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.srcs/sources_1/ip/clk_125m_pll/clk_125m_pll.xci
# IP: The module: 'clk_125m_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/clk_125m_pll/clk_125m_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_125m_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/clk_125m_pll/clk_125m_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_125m_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/clk_125m_pll/clk_125m_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_125m_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.srcs/sources_1/ip/clk_125m_pll/clk_125m_pll.xci
# IP: The module: 'clk_125m_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/clk_125m_pll/clk_125m_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_125m_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/clk_125m_pll/clk_125m_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_125m_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Hiba Tantawi/Desktop/fpga/uOttaHack_FPGA/fpga_top/fpga_top.gen/sources_1/ip/clk_125m_pll/clk_125m_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_125m_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
